name: Android CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Gradle Wrapper
      run: |
        cd mobile
        mkdir -p gradle/wrapper
        wget -O gradle/wrapper/gradle-wrapper.jar https://github.com/gradle/gradle/raw/master/gradle/wrapper/gradle-wrapper.jar
      
    - name: Grant execute permission for gradlew
      run: chmod +x mobile/gradlew
      
    - name: Build with Gradle
      run: cd mobile && ./gradlew build
      
    - name: Build Debug APK
      run: cd mobile && ./gradlew assembleDebug
      
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: mobile/build/outputs/apk/debug/mobile-debug.apk